### ISSUE TITLE
Spec parity?

### ISSUE THREAD

**Issue by erikjung** [jameskolce/postcss-lh#18]
Since it looks like the `lh` and `rlh` units will be a real thing, I was wondering if you intended to make this plugin more of a polyfill and also support the `rlh` unit?

https://drafts.csswg.org/css-values/#lh

I could see this as a nice addition to [cssnext](https://github.com/MoOx/postcss-cssnext).

/CC @MOox

**Comment by jameskolce** [comment]
I actually didn't know about those units in the CSS spec, when that happened?

**Comment by jameskolce** [comment]
Anyway, for me is fine to move to that direction, looks like this one would behave like `rlh`, I don't think `lh` can be implemented though because it is relative to the parent element unless I'm missing something.
